function changeMain(number) {
    let main = document.getElementById('main');
    if (number == 0) {
        main.innerHTML = "<h2>Welcome To The Site</h2><p>Welcome, one and all, to the Internet Union! 😎</p><p><img src='./media/laserkitten2.png' alt='Laser_Cat' width='75%' height='446'><p>Yeah, we are weird, as you may have been able to tell...</p></p><h4 style='text-align: center;' id='myHeader'>Click the button...and change your life forever...</h4><p style='text-align: center;'><button onclick='displayResult()'>Hit me bubby</button></p><p></p><br>"
    } else if (number == 1) {
        main.innerHTML = "<h2>About</h2><p>Why hello, good peoples of the Internet! The Internet Union, in general, is kind of a place to hang out and stuff. You can come here whenever you want and check out content from our little section of the Internet. We'll have videos, polls, news, chat, and maybe more in the future. We hope you enjoy!</p><p>The animated image below is of the creator of this website.</p><p style='text-align:center;'><img src='./media/tmf.gif' alt='Julian_Do' name='Image1' align='center' width='75%' height='446'></p><p style='color:snow'>blog - name:tom password:comein</p>"
    } else if (number == 2) {
        main.innerHTML = "<h2>News</h2><p>Read all the latest updates from the people of the IU. (Note: Only admins can publish news articles since these are taken from the site team's point of view.)</p><div id='content'><table><thead><tr><th class='title'>Title</th><th class='creator'>Creator</th></tr></thead><tbody><tr id='toprow'><td class='title'><p><span><a href='#'>Status Update</a></span></p></td><td class='creator'><span><a href='#'>IUTeam</a></span></td></tr><tr><td class='title'><p><span><a href='#'>Welcome to the Internet Union!</a></span></p></td><td class='creator'><span><a href='#'>IUTeam</a></span></td></tr></tbody></table></div><br>"
    } else if (number == 3) {
        main.innerHTML = "<h2>Videos</h2><p>Watch videos contributed by users from around the site, or make your own!</p><div id='content'><table><thead><tr><th class='thumb'>Thumbnail</th><th class='title'>Title</th><th class='creator'>Creator</th></tr></thead><tbody><tr id='toprow'><td class='thumb'> <img src='./media/gnome-mpv-shot0003.jpg' alt='thumb' width='100px' height='100px'></td><td class='title'><p><span><a href='#'>Roasted Meatloaf S1 E1 - Burger Hut (Pilot Episode)</a></span></p></td><td class='creator'><span><a href='#'>Billy Boy</a></span></td></tr><tr><td class='thumb'> <img src='./media/gnome-mpv-shot0007.jpg' alt='thumb' width='100px' height='100px'></td><td class='title'><p><span><a href='#'>Khan Academy Minecraft Playthrough (Post-Play Commentary)</a></span></p></td><td class='creator'><span><a href='#'>Stagger Lee</a></span></td></tr></tbody></table></div><br>"
    } else if (number == 4) {
        main.innerHTML = "<h2>Polls</h2><p>The voice of the people... and YOUR voice too! Vote for your opinion on polls contributed by users around the site!</p><div id='content'><table><thead><tr><th class='thumb'>Thumbnail</th><th class='title'>Title</th><th class='creator'>Creator</th></tr></thead><tbody><tr id='toprow'><td class='thumb'><img src='./media/swmovies.png' alt='thumb' width='100px' height='100px'></td><td class='title'><p><span><a href='#'>Best Star Wars Movie</a></span></p></td><td class='creator'><span><a href='#'>Billy Boy</a></span></td></tr><tr><td class='thumb'><img src='./media/pollthumb.png' alt='thumb' width='100px' height='100px'></td><td class='title'><p><span><a href='#'>Star Wars vs Star Trek</a></span></p></td><td class='creator'><span><a href='#'>Stagger Lee</a></span></td></tr></tbody></table></div><br>"
    } else if (number == 5) {
        main.innerHTML = "<h2>Games</h2><p>It's time to game on (Sorry if this sounds cringy or something :/)! Play games contributed by users around the site, or make your own!</p><div id='content'><table><thead><tr><th class='thumb'>Thumbnail</th><th class='title'>Title</th><th class='creator'>Creator</th></tr></thead><tbody><tr id='toprow'><td class='thumb'><img src='./media/rmtwg.png' alt='thumb' width='100px' height='100px'></td><td class='title'><p><span><a href='#'>Roasted Meatloaf: The Web Game</a></span></p></td><td class='creator'><span><a href='#'>Billy Boy</a></span></td></tr><tr><td class='thumb'><img src='./media/pack2.png' alt='thumb' width='100px' height='100px'></td><td class='title'><p><span><a href='#'>Simple Train Simulator</a></span></p></td><td class='creator'><span><a href='#'>Stagger Lee</a></span></td></tr></tbody></table></div><br>"
    } else if (number == 6) {
        main.innerHTML = "<h2>Clubs</h2><p>Join clubs, make friends, have a good time, and all that jazz.</p><div id='content'><table><thead><tr><th class='thumb'>Thumbnail</th><th class='title'>Title</th><th class='creator'>Creator</th></tr></thead><tbody><tr id='toprow'><td class='thumb'><img src='./media/socialoutcasts.png' alt='thumb' width='100px' height='100px'></td><td class='title'><p><span><a href='#'>Social Outcasts' Society</a></span></p></td><td class='creator'><span><a href='#'>Billy Boy</a></span></td></tr><tr><td class='thumb'><img src='./media/absolootlibootiful.png' alt='thumb' width='100px' height='100px'></td><td class='title'><p><span><a href='#'>Random Club Thing That No One Cares About</a></span></p></td><td class='creator'><span><a href='#'>Stagger Lee</a></span></td></tr></tbody></table></div><br>"
    } else if (number == 7) {
        main.innerHTML = "<h2>Downloadables</h2><p>Check out downloadable content from users around the site!</p><div id='content'><table><thead><tr><th class='thumb'>Thumbnail</th><th class='title'>Title</th><th class='creator'>Creator</th></tr></thead><tbody><tr id='toprow'><td class='thumb'><img src='./media/foss.png' alt='thumb' width='100px' height='100px'></td><td class='title'><p><span><a href='#'>Free and Open Source Software Collection</a></span></p></td><td class='creator'><span><a href='#'>Billy Boy</a></span></td></tr><tr><td class='thumb'><img src='./media/pack.png' alt='thumb' width='100px' height='100px'></td><td class='title'><p><span><a href='#'>MineWars II: The Resource Awakens</a></span></p></td><td class='creator'><span><a href='#'>Stagger Lee</a></span></td></tr></tbody></table></div><br>"
    } else if (number == 8) {
        main.innerHTML = "<h2>Chat</h2><p>Talk with your friends here. Use the chat thing to talk with your fellow sentient (or A.I.) friends. (Note that all activity can be seen by the site team and any troubling activity will be dealt with in whatever way we can deal with it.)</p><br><form action='chat.php' id='ChatForm' class='chat form-container'><iframe width='100%' height='300px' style='border-color: lightgrey;' src='#'></iframe><br><textarea placeholder='Leave a message...' name='msg' id='message' required></textarea><p style='text-align: center;'><input type='submit' value='Send'></button><input type='reset' value='Cancel'></p></form>"
    } else if (number == 9) {
        main.innerHTML = "<h2>Contact Us</h2><p>Have a question/suggestion? Found a bug you would like to report? Need help? Use the contact form below to let us know!</p><br><div class='container'><div id='contact'><form method='post' action='contact.php'><label for='name'>Name</label><br><input type='text' id='name' name='name' placeholder='Your name...'><br><label for='email'>Email</label><br><input type='text' id='email' name='email' placeholder='Your email...'></input><br><label for='subject'>Subject</label><br><input type='text' id='subject' name='subject' placeholder='Your Subject...'><br><label for='message'>Message</label><br><textarea id='message' name='message' placeholder='Write something...' style='height: 200px; width: 100%;'></textarea><br><input type='submit' value='Submit'></form></div>"
    }
}